### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by paulobocanegra** [mjlomeli/jcp#45]
There are a few things to change in our MVP List.

Products will be one MVP, Shopping Cart will be another MVP.

Under products:
Users will be able to view a list of products
Users will be able to view a specifications for each product

Under shopping cart:
Signed in users will be able to view their shopping cart
Signed in users will be able to add products to the cart
Signed in users will be able to remove products to the cart

Let's change Comments/Ratings to Reviews. Furthermore, will users be able to update/delete their own reviews? If so, let's add those bullet points

**Comment by mjlomeli** [comment]
Thank you!!

### Products
```diff
+ Users will be able to view products.
+ Products lists descriptions and price.
```

### Carts
```diff
+ Users can view the shopping cart.
+ Logged-in users can add to the cart.
+ Logged-in users can edit their existing cart.
```

### Reviews
Comments/Ratings was changed to Reviews. I think its important to edit and delete a review. Also to meet the Edit/Delete requirements.
```diff
- Comments/Ratings
+ Reviews.
+ A user may update/delete a review.
```

Resolved?

**Comment by paulobocanegra** [comment]
Great Job!
