### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by paulobocanegra** [mjlomeli/jcp#46]
Although I appreciate your creativity with the pictures of your table, we want to set up our schema with the table markdown generator: https://www.tablesgenerator.com/markdown_tables

Once you do, Let's add the column for description where we specify the details for the given column like null constrains & indexing. Below each table we need to specify which columns are index in the same format as bluebird: https://github.com/appacademy/bluebird/wiki/schema

*Remember to use back ticks for table names and column names.

**Comment by mjlomeli** [comment]
I agree. The image doesn't showcase my knowledge of Markdown. I have completely renewed the Schema page.

```diff
- svg images
+ Markdown tables

+ description column, having null constrains and indexing.
+ under table specification of references and index.

+ backticks on column names.
```

Resolved?
