### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by paulobocanegra** [mjlomeli/jcp#47]
Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by paulobocanegra** [comment]
I noticed that you left a comment on the page where you specified that you are still working on it so I left a couple of bullet points to focus on. 

For this one: [ ]All keys within the values in the state are accessible in the schema
-> We are just missing the description key for products.

Finally:
-> Let's add a couple more products, users, and reviews.

**Comment by mjlomeli** [comment]
@paulobocanegra 
Yes! Thank you for noticing. I'll update it by Friday. 

Today:
I'm really nitpicking the generics of what we learned by speaking it out loud and breaking the parts further down with so much detail.
- [x] Redux life cycle (tracing and tracing the code)
- [x] Rails API
- [x] Ajax requests
- [ ] Auth
- [ ] Routes
- [ ] withRouter

Tomorrow:
I'll be looking into advance problems (by advance problems I mean further advancing my knowledge).
- [ ] local storage, context api
- [ ] advance middleware with subscribed listeners using 'store enhancers'
- [ ] Rails response types
- [ ] Error page listeners/setup (e.g. Custom exceptions if needed)
- [ ] Project management with webpack.config (e.g. directory imports, svg imports, etc)

(PS: I'm able to pass the all the tests :D )

Tomorrow Night:
- [x] Finally make a managed decision of how all the above and "yesterdays" knowledge will affect the sample state and publish it on the wiki so it can be read by Friday.

**Comment by mjlomeli** [comment]
@paulobocanegra 

Its been updated. Thank you for explaining today!

Resolved?

**Comment by paulobocanegra** [comment]
Great job!
