### ISSUE TITLE
Frond End Routes

### ISSUE THREAD

**Issue by paulobocanegra** [mjlomeli/jcp#48]
We need to update our frontend routes:

Frontend Routes

- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

We need to specify what components will be rendered for each front end route:

Product
`/product/:productId`
        `ProductShow`
        `ReviewIndex`
        `ReviewForm`

^ That is an example for a product show page

/product/:product_id/review - Gets the product reviews (maybe not necessary).
^ That is correct, we can render all the reviews on the same product page

The same goes for:
/reviews/:review_id/ - Gets the review of a product (maybe not necessary).
/reviews/:product_id - Gets the review of a product.

Reviews will be listed under a product show page or a user profile page, I can't think of a case were we would be rendering just reviews independent from either what they are for or who made it.

{

 User + Product
/users/:user_id/product/:product_id - Gets a user's "product store".
/users/:user_id/product/:product_id/new - User adds a product a user's store.
/users/:user_id/product/:product_id/edit - User edits a product from their store.
/users/:user_id/product/:product_id/delete - Removes a product from the cart.

User + Cart
/users/:user_id/cart - Gets the user's cart.
/users/:user_id/cart/:product_id/new - Adds a product to the cart (to be modified).
/users/:user_id/cart/:product_id/edit - Edits the cart.
/users/:user_id/cart/:product_id/delete - Removes a product from the cart.

}
^ There is no need for any of there routes.

Remember that front end routes are very different than backend routes.

If you want to add a front end route for your cart (to show all products and have a "checkout page") all you need is a route for 

/cart
    CartIndex
    CartIndexItem

for products:

/products
      ProductIndex
      ProductIndexItem

/products/:productId
      ProductShow
      ReviewIndex
      Review Form

Here is a reference to what you want these routes to look like:
https://github.com/appacademy/bluebird/wiki/frontend-routes

**Comment by mjlomeli** [comment]
@paulobocanegra 
You are right! Second look at it today after studying and the bigger picture is much more clearer. I've already updated it. Added some style to attempt readability. Otherwise, I can revert it back to bullet points.

[Link to Wiki: Frontend-Routes](https://github.com/mjlomeli/jcp/wiki/Frontend-Routes)

```diff
- user_id
+ userId

- product_id
+ productId


- review_id
+ reviewId

- order_id
+ orderId

- User + Product
- User + Cart
- User + Order

+   Components

```
[Link to Wiki: Frontend-Routes](https://github.com/mjlomeli/jcp/wiki/Frontend-Routes)

Resolved?
