### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by paulobocanegra** [mjlomeli/jcp#49]
Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by paulobocanegra** [comment]
Review
GET /api/users - Returns the reviews of a user (to be modified).
POST /api/users/product_id - Writes a review of a product.

^ /api/users/:user_id/reviews    would get you all the reviews that user has made
/api/products/:product_id/reviews    would get you all the reviews for a product


UPDATE /api/users/id/product/id - Adds a product to the cart (to be modified). 
^ POST and it would be for /api/cart_items

DELETE for /api/cart_items/:cart_item_id to remove an item from the cart. 

Remember that we only keep one session and we know exactly who the current_user is, you don't need to nest everything under /users/:user_id

From the above I hope you get the point. Let me know if you need to meet to talk about both front end and backend routes.

**Comment by paulobocanegra** [comment]
https://github.com/appacademy/bluebird/wiki/backend-routes

**Comment by mjlomeli** [comment]
@paulobocanegra well, this was embarrassing. All of the backend routes was completely and absolutely a bogus copy and paste template, not even a rough draft :D. I thought it was only the state sample I need to focus on.

Its updated now.

[Link to: Backend-Routes](https://github.com/mjlomeli/jcp/wiki/Backend-Routes)

Resolved?
